title: Steven Black Consulting
url: http://stevenblack.com
metakeywords: "Steven Black, Project Manager, Project Turnarounds, Web Developer, Wiki Meister, INTL, INTL Toolkit, Visual FoxPro, Object Oriented Analysis and Design, OOAD, OOP, Mentoring, Multilingual Application Development, Client/Server Databases, Project Leadership, Training, Consulting"
metadescription: "Website of Steven Black Consulting"
permalink: /articles/:title/
analytics: UA-212713-3

posts: posts

# images
image_default_alt: Steven Black Consulting

exclude: [ ".git", "Rakefile", ".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", "_site/font-awesome/docs/" ]
